name: pmd-winter-2026
recipe: drupal11
config:
  php: "8.3"
  via: apache:2.4
  database: mysql:8.0
  composer_version: 2-latest
  drush: ^13
  webroot: web
services:
  appserver:
    config:
      php: php.ini
    overrides:
      environment:
        XDEBUG_MODE: debug,develop
        DRUSH_OPTIONS_URI: "http://pmd-winter-2026.lndo.site"
  dba:
    type: phpmyadmin
